version: '3.7'

services:
  database:
    image: mysql:5.7
    restart: always
    volumes:
      - mydata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER:   wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      -  wpnet
  wordpress:
    image: wordpress:latest
    depends_on:
    - database
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: mydata:3306
      WORDPRESS_DB_USER:  wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      -  wpnet

volumes:
  mydata:



networks:
  wpnet:
    driver: bridge


