version: '3.7'

services:
  daatabase:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD:  1
      MYSQL_DATABASE: wordpress
      MYSQL_USER:  wordpress
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    secrets:
      - mysql_password
    networks:
      - wp_overlay

  wordpress:
    image: wordpress:latest
    depends_on:
      - database
    environment:
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSOWRD_FILE: /run/secrets/mysql_password
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wp_overlay
    ports:
      - "8080:80"
    deploy:
        replicas: 3
        update_config:
          parallelism: 2
          delay: 10s


networks:
  wp_overlay:
    driver: overlay
secrets:
  mysql_password: 
    file: mysqlpass.txt

# volumes:
  